username = input("Введите имя пользователя: ")
title = input("Введите заголовок заметки: ")
content = input("Введите описание заметки: ")
status = input("Введите статус заметки (например, 'Активна', 'Выполнена'): ")
created_date = input("Введите дату создания заметки в формате 'дд-мм-гггг': ")
issue_date = input("Введите дату истечения заметки в формате 'дд-мм-гггг': ")


print("\nВы ввели следующие данные:")
print("Имя пользователя:", username.title())
print("Заголовок заметки:", title.capitalize())
print("Описание заметки:", content.capitalize())
print("Статус заметки:", status.capitalize())
print("Дата создания заметки:", created_date [:5])
print("Дата истечения заметки:", issue_date [:5])
